// Generated by flutterfire configure — project: iot-platform-6b89a
// DO NOT edit manually; re-run `flutterfire configure` to regenerate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS     => ios,
      _ => throw UnsupportedError(
            'DefaultFirebaseOptions not supported on this platform'),
    };
  }

  // ── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'AIzaSyAY5wVvaQh4oC8CTsK6-JsWvawbVH9tDSY',
    authDomain:        'iot-platform-6b89a.firebaseapp.com',
    projectId:         'iot-platform-6b89a',
    storageBucket:     'iot-platform-6b89a.appspot.com',
    messagingSenderId: '20870417560',
    appId:             '1:20870417560:web:26b62c256f363a520594ed',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyAwe_6bC6z7_HHjk1kP4A-81OfQfplE234',
    appId:             '1:20870417560:android:9229fbae47b554b70594ed',
    messagingSenderId: '20870417560',
    projectId:         'iot-platform-6b89a',
    storageBucket:     'iot-platform-6b89a.firebasestorage.app',
  );

  // ── iOS ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'AIzaSyCP59d-RZ8-bf3vcMSP_mvvZOHMco6nDGI',
    appId:             '1:20870417560:ios:1d99c0b7c93143520594ed',
    messagingSenderId: '20870417560',
    projectId:         'iot-platform-6b89a',
    storageBucket:     'iot-platform-6b89a.firebasestorage.app',
    iosClientId:       '20870417560-hgamfseh63i4ssv08qfs02r8c6q8q58o.apps.googleusercontent.com',
    iosBundleId:       'com.example.iotCompanion',
  );
}
